"""Stack setup execution — clone OCR repo, generate compose, start services."""
from __future__ import annotations

import os
import secrets
import subprocess
from dataclasses import dataclass, field
from pathlib import Path

from rich.console import Console

console = Console()


OCR_REPO_DEFAULT = "https://github.com/phungkien402/ocr.git"
OCR_BRANCH_DEFAULT = "sub_main"
WORKDIR_DEFAULT = "~/OCR_PHR"


@dataclass
class StackConfig:
    bv_name: str
    repo_url: str = OCR_REPO_DEFAULT
    branch: str = OCR_BRANCH_DEFAULT
    workdir: str = WORKDIR_DEFAULT
    enable_funnel: bool = True
    ocr_port: int = 7005
    proxy_port: int = 8081
    qwen_url: str = "http://localhost:8080"
    medgemma_url: str = "http://localhost:8082"
    generated: dict[str, str] = field(default_factory=dict)


def _gen_key() -> str:
    return secrets.token_hex(32)


def _expand(p: str) -> Path:
    return Path(os.path.expanduser(p)).resolve()


def _run(cmd: list[str] | str, cwd: Path | None = None, check: bool = True) -> int:
    console.print(f"  [dim]$ {cmd if isinstance(cmd, str) else ' '.join(cmd)}[/]")
    r = subprocess.run(cmd, cwd=cwd, shell=isinstance(cmd, str), check=False)
    if check and r.returncode != 0:
        raise RuntimeError(f"Command failed (exit {r.returncode}): {cmd}")
    return r.returncode


def clone_or_update(cfg: StackConfig) -> Path:
    """Clone OCR repo nếu chưa có, hoặc pull update."""
    workdir = _expand(cfg.workdir)
    if (workdir / ".git").exists():
        console.print(f"[dim]Repo exists, fetching updates...[/]")
        _run(["git", "fetch", "--all"], cwd=workdir)
        _run(["git", "checkout", cfg.branch], cwd=workdir, check=False)
        _run(["git", "pull", "origin", cfg.branch], cwd=workdir, check=False)
    else:
        workdir.parent.mkdir(parents=True, exist_ok=True)
        _run(["git", "clone", "-b", cfg.branch, cfg.repo_url, str(workdir)])
    return workdir


def generate_env(workdir: Path, cfg: StackConfig) -> dict[str, str]:
    """Generate OCR_server/.env + .env (top-level) + .vllm_proxy.env."""
    ocr_key = _gen_key()
    proxy_key = _gen_key()

    ocr_env = workdir / "OCR_server" / ".env"
    ocr_env.parent.mkdir(parents=True, exist_ok=True)
    ocr_env.write_text(
        f"# Generated by ehc-installer for {cfg.bv_name}\n"
        f"OCR_API_KEY={ocr_key}\n"
        f"VLM_ENDPOINT=http://host.docker.internal:8080/v1/chat/completions\n"
        f"STORAGE_PATH=/app/OCR_server/data/ocr_storage\n"
        f"AUTH_ENABLED=true\n"
        f"RATE_LIMIT=60/minute\n"
    )
    ocr_env.chmod(0o600)

    top_env = workdir / ".env"
    if not top_env.exists():
        top_env.write_text(
            f"# Generated by ehc-installer\n"
            f"# Dummy ngrok token (legacy compose may require it)\n"
            f"NGROK_AUTHTOKEN=dummy_not_used\n"
            f"TG_BOT_TOKEN=\n"
            f"TG_CHAT_ID=\n"
        )

    proxy_env = workdir / ".vllm_proxy.env"
    proxy_env.write_text(
        f"VLLM_PROXY_KEY={proxy_key}\n"
        f"VLLM_QWEN_URL={cfg.qwen_url}\n"
        f"VLLM_MEDGEMMA_URL={cfg.medgemma_url}\n"
        f"VLLM_PROXY_PORT={cfg.proxy_port}\n"
    )
    proxy_env.chmod(0o600)

    return {
        "OCR_API_KEY": ocr_key,
        "VLLM_PROXY_KEY": proxy_key,
    }


def copy_proxy_script(workdir: Path) -> None:
    """Copy tools/vllm_auth_proxy.py từ OCR repo (đã có sẵn trong repo)."""
    src = workdir / "tools" / "vllm_auth_proxy.py"
    if not src.exists():
        console.print(f"  [yellow]⚠ {src} not found in repo. Auth proxy có thể chưa hoạt động.[/]")


def start_compose(workdir: Path) -> None:
    """docker compose up -d."""
    uid = os.getuid() if hasattr(os, "getuid") else 1000
    gid = os.getgid() if hasattr(os, "getgid") else 1000

    env = os.environ.copy()
    env["OCR_UID"] = str(uid)
    env["OCR_GID"] = str(gid)

    console.print("[bold]Building + starting ocr-server...[/]")
    subprocess.run(
        ["docker", "compose", "build", "ocr-server"],
        cwd=workdir, env=env, check=True,
    )
    subprocess.run(
        ["docker", "compose", "up", "-d"],
        cwd=workdir, env=env, check=True,
    )


def start_auth_proxy(workdir: Path) -> None:
    """Background python tools/vllm_auth_proxy.py với env file."""
    proxy_script = workdir / "tools" / "vllm_auth_proxy.py"
    env_file = workdir / ".vllm_proxy.env"
    log_file = workdir / "vllm_proxy.log"

    if not proxy_script.exists():
        console.print(f"  [yellow]⚠ {proxy_script} missing — skip starting proxy[/]")
        return

    # Kill existing
    subprocess.run(["pkill", "-f", "vllm_auth_proxy.py"], capture_output=True)

    # Build env vars from env file
    env_vars = {}
    if env_file.exists():
        for line in env_file.read_text().splitlines():
            line = line.strip()
            if "=" in line and not line.startswith("#"):
                k, _, v = line.partition("=")
                env_vars[k.strip()] = v.strip()

    env = os.environ.copy() | env_vars

    # Background process
    with open(log_file, "ab") as logf:
        subprocess.Popen(
            ["python3", str(proxy_script)],
            cwd=workdir,
            env=env,
            stdout=logf,
            stderr=logf,
            start_new_session=True,
        )
    console.print(f"  [green]✓ Auth proxy started → {log_file}[/]")


def setup_tailscale(cfg: StackConfig) -> str | None:
    """Tailscale up + enable Funnel cho OCR (port 443→7005) và proxy (port 8443→8081)."""
    # Detect if user logged in
    r = subprocess.run(["tailscale", "status", "--json"], capture_output=True, text=True)
    if r.returncode != 0:
        console.print("  [yellow]Tailscale not ready. Run [bold]sudo tailscale up --hostname=" + cfg.bv_name + "[/] manually.[/]")
        return None

    # Try set hostname
    subprocess.run(["sudo", "tailscale", "set", "--hostname=" + cfg.bv_name], check=False)

    if not cfg.enable_funnel:
        return None

    # Enable Funnel for OCR + proxy
    subprocess.run(["sudo", "tailscale", "funnel", "--bg", str(cfg.ocr_port)], check=False)
    subprocess.run(["sudo", "tailscale", "funnel", "--bg", "--https=8443", str(cfg.proxy_port)], check=False)

    # Get URL
    r = subprocess.run(["tailscale", "funnel", "status"], capture_output=True, text=True)
    for line in r.stdout.splitlines():
        if "ts.net" in line and "https://" in line:
            return line.strip().split()[0]
    return None


def setup_full(cfg: StackConfig) -> dict:
    """Full setup pipeline. Return summary dict."""
    summary: dict[str, str] = {"bv_name": cfg.bv_name}

    console.print(f"\n[bold cyan]→ Stack setup for [/][bold]{cfg.bv_name}[/]\n")

    console.print("[bold]1. Clone/update OCR repo[/]")
    workdir = clone_or_update(cfg)
    summary["workdir"] = str(workdir)

    console.print("\n[bold]2. Generate .env files[/]")
    tokens = generate_env(workdir, cfg)
    summary.update(tokens)

    console.print("\n[bold]3. Copy auth proxy script[/]")
    copy_proxy_script(workdir)

    console.print("\n[bold]4. Build + start docker compose[/]")
    try:
        start_compose(workdir)
    except subprocess.CalledProcessError as e:
        console.print(f"  [red]✗ docker compose failed: {e}[/]")
        return summary

    console.print("\n[bold]5. Start auth proxy[/]")
    start_auth_proxy(workdir)

    if cfg.enable_funnel:
        console.print("\n[bold]6. Setup Tailscale Funnel[/]")
        url = setup_tailscale(cfg)
        if url:
            summary["public_url"] = url

    return summary


def print_handover(summary: dict) -> None:
    """In doc handover cho HIS / CDSS team."""
    console.print("\n[bold green]═══ Setup complete ═══[/]\n")
    console.print(f"[bold]BV name:[/]      {summary.get('bv_name', '?')}")
    console.print(f"[bold]Workdir:[/]      {summary.get('workdir', '?')}")
    if "public_url" in summary:
        console.print(f"[bold]Public URL:[/]   {summary['public_url']}")
        console.print(f"  OCR API:    {summary['public_url']}/v1/extract")
        console.print(f"  CDSS API:   {summary['public_url'].rstrip('/')}:8443/v1/chat/completions")
    console.print()
    console.print(f"[bold]OCR API key:[/]      [yellow]{summary.get('OCR_API_KEY', '?')}[/]")
    console.print(f"[bold]CDSS proxy key:[/]   [yellow]{summary.get('VLLM_PROXY_KEY', '?')}[/]")
    console.print("\n[red]⚠ Keys gửi qua kênh bảo mật (Slack DM / Zalo riêng), không paste public.[/]\n")
